:toc:
:toclevels: 4

= Picky PowerShell Cmdlet

Picky is a PowerShell cmdlet for Picky Server, to sign the certificate etc.

== Installation

=== PowerShell Core
On Windows, the regular PowerShell already installed can be used. On macOS and Linux, you need PowerShell Core 6.0:

PowerShell Core 6.0::
https://github.com/PowerShell/PowerShell#get-powershell

To launch a PowerShell Core terminal, use the `pwsh` command.

==== Installation from Source

To build the Cmdlet, you will need the .NET Core 2.2 SDK and the .NET Framework 4.7.2 SDK. The latter is only needed if you want to support PowerShell for Windows.

 .NET Core 2.2 SDK::
https://dotnet.microsoft.com/download

 .NET Framework 4.7.2 SDK::
https://dotnet.microsoft.com/download/dotnet-framework/net472

From PowerShell, run the build.ps1 script, and then load the resulting PowerShell module:

[source,sh]
----
PS > Import-Module ./Picky.psd1 -Force
----

=== Docker Installation

Picky need to run it's server inside Docker containers. The PowerShell cmdlet simplifies the usage of Docker for users not familiar with it. For more advanced users, the cmdlet can export a usable docker-compose configuration file.

On Windows, the recommended option is to use https://hub.docker.com/editions/community/docker-ce-desktop-windows[Docker Desktop for Windows]. This version of Docker requires Hyper-V for Linux container support.

For bind mount support with Linux containers on Windows, you need to go in the Docker settings and https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c[select the required drives from the "Shared Drives" section].

On macOS and Linux, follow the instructions here to install Docker CE correctly. It is recommended to use the official Docker packages instead as documented in the https://docs.docker.com/install/[Docker install page].

On Linux, do not forget to https://docs.docker.com/install/linux/linux-postinstall/[add your user to the docker group] after installation.

To confirm that Docker is up and running, use the `docker run hello-world` command. If you don't see the "Hello from Docker!" message, something is wrong with your Docker installation.

== Running

Start Picky, and wait for server to start: 

There is facultative parameters:

- `PickyUrl`, the url with the port for your Picky Server, the default value is 'http://127.0.0.1:12345'

- `PickyApiKey`, the api key for the Picky Server, the default value is a guid

- `PickyDockerImage`, the docker image to pull for Picky Server, the default value is 'devolutions/picky:3.3.0-buster-dev'

- `PickyRealm`, the realm of the Picky Server, the default value is 'wayk.net'

- `PickyBackend`, what to use to store the backend of Picky Server, the default value is 'mongodb'

- `PickyDatabaseUrl`, the database url of the backend of Picky Server, the default value is 'mongodb://picky-mongo:27017'

[source, sh]
----
PS > Start-PickyServer -PickyApiKey 123456 -PickyRealm Wayk.net   
----


Stop Picky Server, and wait for server to stop:

[source, sh]
----
PS > Stop-PickyServer
----

Restart Picky Server, with the same parameters than Start-PickyServer:

[source, sh]
----
PS > Restart-PickyServer -PickyApiKey 123456 -PickyRealm Wayk.net   
----

== Certificate Management

=== Request Certificate
Picky sign a CSR with his root CA, with the command `Request-Certificate`, a CSR will be created and send to Picky Server to be signed, the signed certificate is returned.

The parameters are needed:

- `Subject`, the subject of your CSR for Picky Server

- `PickyApiKey`, the Api Key of your Picky Server.

- `PickyUrl`, (Facultative) the url with the port for your Picky Server, the default value is 'http://127.0.0.1:12345'


[source, sh]
----
PS > Request-Certificate -Subject MySubject -PickyApiKey 123456
----

The ID of the certificate will be returned as a result.

[source, sh]
----
6462eb3e-addb-499a-9727-894994b22ed8
----

=== Get Certificates
The list of signed certificates can be shown with the command `Get-LocalCertificates`

[source, sh]
----
PS > Get-LocalCertificates
----

The result:

[source, sh]
----
Issuer                Subject     ID
------                -------     --
CN=Wayk.net Authority John        2c082069-5281-4ed4-aadb-cd0fbb15bc30
CN=Wayk.net Authority Marie       39f69f39-6eec-4aa3-9663-4a4ae37b90b5
----

=== Save Certificate on Server
You can save certificates that have been signed on the backend of the Picky server with the `Save-CertificateOnServer` command.

Required parameters are:

- `PickyApiKey`, the Api Key of your Picky Server.

- `CertificateID`, The ID of the certificate

- `PickyUrl`, (Facultative) url and port to your Picky Server, the default value is 'http://127.0.0.1:12345'


[source, sh]
----
PS > Save-CertificateOnServer -PickyApiKey 123456 -CertificateID 2c082069-5281-4ed4-aadb-cd0fbb15bc30
----

=== Remove Certificate
TODO Remove Certificate on the Picky Server

You can remove certificate with the command `Remove-LocalCertificate`

The parameters are needed:

- `CertificateID`, The ID of the certificate

[source, sh]
----
PS > Remove-LocalCertificate -CertificateID 2c082069-5281-4ed4-aadb-cd0fbb15bc30
----

=== Save Root CA Certificate
The command `Save-RootCaCertificate` will save localy the root ca of your Picky-Server

The parameters are:

- `PickyUrl`, (Facultative) url and port to your Picky Server, the default value is 'http://127.0.0.1:12345'

[source, sh]
----

PS > Save-RootCaCertificate
----

=== Store Trust Certificate
The command `Set-TrustStoreCertificate` will save your certificate to the trust store of your platform.

The parameters are needed:

- `RootCertificatePath`, the path of the Root CA certificate

[source, sh]
----
PS > Set-TrustStoreCertificate -RootCertificatePath C:\Users\user\Downloads\root_ca.pem
----
